import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import "../src/assets/css/main.css";
import Antd from "ant-design-vue";
import "ant-design-vue/dist/reset.css";
import { createPinia } from "pinia";
// import { QuillEditor } from "@vueup/vue-quill";
import CKEditor from "@ckeditor/ckeditor5-vue";
// import "@vueup/vue-quill/dist/vue-quill.snow.css";
// import "@vueup/vue-quill/dist/vue-quill.bubble.css";
import BootstrapVue3 from "bootstrap-vue-3";
const pinia = createPinia();
const app = createApp(App);

app.use(pinia);
app.use(Antd);
app.use(router);
app.use(BootstrapVue3);
// app.component("QuillEditor", QuillEditor);
app.use(CKEditor);
app.mount("#app");
